### ISSUE TITLE
[3495] rest_prepare_latest arguments are wrong

### ISSUE THREAD

**Issue by SantosGuillamot** [wp-pwa/wp-plugin#101]
`rest_prepare_latest` should have the same arguments than the other `rest_prepare_...`: `$response`, `$item`, `$request`: https://developer.wordpress.org/reference/hooks/rest_prepare_this-taxonomy/

`rest_prepare_latest` is here:
https://github.com/frontity/wp-plugin/blob/377c45c454082dd32bec338adeec5024b72b8c90/wp-pwa.php#L273

----
#cs: @SantosGuillamot 
#supporter: @luisherranz 

https://frontity.pipedrive.com/deal/8
Pageviews: **(11.65)**
Environment: **integration is finishing (x6)**
Range: **low (x1)**
Behaviour: **no frontity without it (x10)**
Mass: **everyone (x5)**
PRIORITY: **[3495]**

**Comment by luisherranz** [comment]
This is the line:
https://github.com/frontity/wp-plugin/blob/377c45c454082dd32bec338adeec5024b72b8c90/wp-pwa.php#L273
