### ISSUE TITLE
[188] Htmlpurifier outputs weird html

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/wp-plugin#29]
It outputs this html:
```html
<p>#td_uid_1_5bb370e5be870.td-doubleSlider-2.td-item1{background:url(https://arquitecturaideal.com/wp-content/uploads/2018/09/gan-bedroom-projects-catania-80x60.jpg)00no-repeat;}#td_uid_1_5bb370e5be870.td-doubleSlider-2.td-item2{background:url(https://arquitecturaideal.com/wp-content/uploads/2018/09/gan-bedroom-projects-indigo-80x60.jpg)00no-repeat;}#td_uid_1_5bb370e5be870.td-doubleSlider-2.td-item3{background:url(https://arquitecturaideal.com/wp-content/uploads/2018/09/gan-bedroom-projects-mangas-original-80x60.jpg)00no-repeat;}#td_uid_1_5bb370e5be870.td-doubleSlider-2.td-item4{background:url(https://arquitecturaideal.com/wp-content/uploads/2018/09/gan-bedroom-projects-mangas-space-80x60.jpg)00no-repeat;}#td_uid_1_5bb370e5be870.td-doubleSlider-2.td-item5{background:url(https://arquitecturaideal.com/wp-content/uploads/2018/09/gan-bedroom-projects-mirage-80x60.jpg)00no-repeat;}#td_uid_1_5bb370e5be870.td-doubleSlider-2.td-item6{background:url(https://arquitecturaideal.com/wp-content/uploads/2018/09/gan-bedroom-projects-rodas-80x60.jpg)00no-repeat;}#td_uid_1_5bb370e5be870.td-doubleSlider-2.td-item7{background:url(https://arquitecturaideal.com/wp-content/uploads/2018/09/gan-bedroom-projects-sioux-80x60.jpg)00no-repeat;}</p>
```

in this endpoint:
https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A14

for this url:
https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A15

Requires https://github.com/frontity/wp-plugin/issues/30
Requires https://github.com/frontity/wp-plugin/issues/36

----
https://frontity.pipedrive.com/deal/253
Size: **(0.1M)**
Environment: **production (x10)**
Range: **low (x1)**
Behaviour: **critical (x5)**
Mass: **everyone (x5)**
PRIORITY: **[25]**

https://frontity.pipedrive.com/deal/246
Pageviews: **(0.41)**
Environment: **production (x10)**
Range: **low (x1)**
Behaviour: **critical (x5)**
Mass: **everyone (x5)**
PRIORITY: **[103]**

Pageviews: **(0.24)**
Environment: **production (x10)**
Range: **low (x1)**
Behaviour: **critical (x5)**
Mass: **everyone (x5)**
PRIORITY: **[60]**

**Comment by luisherranz** [comment]
Requires https://github.com/frontity/wp-plugin/issues/30.

**Comment by luisherranz** [comment]
In PHP you can get a query using `isset($_GET['name'])`.

**Comment by DAreRodz** [comment]
The client has updated our plugin:
https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A16

I'm going to remove the 'blocked' tag

**Comment by DAreRodz** [comment]
Maybe it is not enough to disable the htmlPurifier, as the content we receive from the API could be being processed by other plugin or WordPress itself (see https://codex.wordpress.org/How_WordPress_Processes_Post_Content).

Using the content received form the request above doesn't reproduce the issue in a local environment.
@luisherranz , @orballo , any ideas?

**Comment by luisherranz** [comment]
I'm really lost in this one. It can't be something WP is processing because the only difference is the htmlpurifier.

Things that come to my mind, but I've no confidence in being the problem, to be honest:
- The PHP version is old and something in htmlpurifier doesn't work as expected in that version.
- The internal cache is somewhat broken and it's returning an old version.

@SantosGuillamot could you please tell the customer to tell us his PHP version and to purge the htmlpurifier cache using the advanced options of the plugin? Then answer here and unblock the issue.

**Comment by SantosGuillamot** [comment]
Yes, I will let you know as soon as they tell me anything

**Comment by luisherranz** [comment]
Thanks @SantosGuillamot!

**Comment by SantosGuillamot** [comment]
He told us the PHP version that is using is 5.6.99-hhvm and the cache is purged.

I remove the 'blocked' label

**Comment by luisherranz** [comment]
Thanks @SantosGuillamot. We can discard those two problems. Maybe we need to know what's in the database because there has to be something weird somewhere. I'll think what we can do and I'll let you know.

**Comment by luisherranz** [comment]
@SantosGuillamot can you ask the guy to take a look at MySQL and send us the exact content of the database? The query is: `SELECT post_content FROM wp_posts WHERE ID = 11541` although he may have to adapt it to his database table name. 

Also, a list of active plugins could be useful. Maybe we can reproduce it with those.

**Comment by SantosGuillamot** [comment]
I have just asked him about the database and the plugins, I will let you know as soon as we get an answer. Should we 'blocked' the issue while we are waiting for customer response?

**Comment by SantosGuillamot** [comment]
The list of plugins:

AmpedSense - AdSense Split Tester
Antispam Bee
Contact Form 7
Easy Post Embed Code
Filenames to latin
GDPR Cookie Consent
Instant Articles for WP
NextScripts: SNAP Pro Upgrade Helper
NextScripts: Social Networks Auto-Poster
OneSignal Push Notifications
Page Links To
Requerir imagen destacada
Revive Old Post (anteriormente Tweet Old Post)
Revive old post Pro Add-on
SCHEMA for Article
tagDiv Speed Booster
Tiled Galleries Carousel Without Jetpack
W3 Total Cache
WordPress PWA
WP Missed Schedule
WP to Buffer Pro
WPBakery Page Builder
Yoast SEO

**Comment by luisherranz** [comment]
> Should we 'blocked' the issue while we are waiting for customer response?

Yep, blocked until he answers with the database info.

**Comment by SantosGuillamot** [comment]
We have detected it in another url:
https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A47

**Comment by luisherranz** [comment]
We have finally found out what it is: when a tag `<style>...</style>` is present, we remove the `<style>` tag but the content remains. We should get rid of the tag along with the inner content.

**Comment by luisherranz** [comment]
@orballo could you please add this fix to the next release? Thanks!

**Comment by orballo** [comment]
yes, ofc :)

**Comment by orballo** [comment]
@luisherranz that doesn't seem to be the problem because I'm pasting the content from the REST API without purifying and the `<style>` tag is parsed correctly. I can't reproduce the problem in local.
@mario Did we got the original content from the client?

**Comment by luisherranz** [comment]
@SantosGuillamot you should send the customer information about how to fix this broken HTML as there's nothing we can do from here. 

I'll close the issue now.
