### ISSUE TITLE
Fix 403 images in REST responses

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/wp-plugin#46]
Sometimes, images don't show up in the REST API due to a 403 (forbidden) error. More on this here: https://support.frontity.com/troubleshooting/some-images-dont-appear

To solve the problem, those images must be unattached, which is equal to set their `post` property set to `null`. For example, this is an image attached to the 3076 post:
https://blog.frontity.com/?rest_route=/wp/v2/media/3090
(`post` is `3076`)
And this is an unattached image:
https://blog.frontity.com/?rest_route=/wp/v2/media/487
(`post` is `null`).

From a quick investigation, I think this could work:
- Once we have the ID of an image, it's fast to retrieve the object. I think we can use [get_post](https://developer.wordpress.org/reference/functions/get_post/) for that. 
- If `post` is `null`, we are good to go.
- If `post` is a real post, we need to check the post status.
- If it is published, we are good to go.
- If it is `draft`, `trashed`, no longer exists... and so on, we need to set `post` to `null` in the original image. That's the same than doing an `unattach` in the WP dashboard. I think we can use [wp_update_attachment_metadata](https://codex.wordpress.org/Function_Reference/wp_update_attachment_metadata).

-----

https://frontity.pipedrive.com/deal/44

**Comment by DAreRodz** [comment]
It should be active only when the query `fixForbiddenMedia=true` is present.

**Comment by DAreRodz** [comment]
It should also fix `featured_media`.
