### ISSUE TITLE
[1350] Youtube videos are not showing in REST API

### ISSUE THREAD

**Issue by SantosGuillamot** [wp-pwa/wp-plugin#48]
Although youtube iframe is included in the page source, it doesn't appear in the API. It seems to be a problem with htmlpurifier

This is an example, but the error appears in all the posts with Youtube videos of this web:
https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A17

Page source
![Screen Shot 2018-10-31 at 14.15.23.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b9625a0f85c42001167f9b7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236457f26b7191a379eb0c2a54415d4dbe5d4a1f06a3a3dc78e2a436628f0e0feed2695875c23d42afbd811fbf03bc72d84bd4e3e89850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecc58ff42e74b5ca01b3063f43b.png)

API
![https___toppercan_es_wp-json_wp_v2_posts_slug_perro-policia-maniobra-reanimacion.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b9625a0f85c42001167f9b7/125516c66e82c728ace21e0d46e0808e3391bc96b0fdb053b458e297284818763a3bb43b3d8ff027b17d6c1130194cc301071c00bf96ca77e3e15330df1e49b2cc2d00289f6e48fda5df4ee158e572c91e98f4e9db1299b56c76bed4d15d220c455ad6a50866e48b41da5da44fe24e51a3123263b575337f47941c737e386377fea8cd4a95c731faee4f720f82b6a6e81c00a07bd2c60c75635c52ac2d32b0045f8d72d5.png)

----
Size: **(3M)**
Environment: **production (x10)**
Range: **medium (x3)**
Behaviour: **not-nice (x1)**
Mass: **everyone (x5)**
Miscelanea: **referrer (x3)**
PRIORITY: **[1350]**

https://frontity.pipedrive.com/deal/54

**Comment by DAreRodz** [comment]
I's a problem filtering empty elements with HtmlPurifier.
