### ISSUE TITLE
Expose the blog-url in latest when home is set to a page

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/wp-plugin#5]
Here, the latest link is showing https://herencia.net/archivos/ and it should show https://herencia.net/:

https://herencia.net/wp-json/wp/v2/posts/49593?_embed=true

Child of https://github.com/frontity/wp-plugin/issues/11

**Comment by Poliuk** [comment]
Once you close this issue, please let me know :)

**Comment by luisherranz** [comment]
Sure!
