### ISSUE TITLE
[18000] If image is not found, data-attachment should not appear

### ISSUE THREAD

**Issue by SantosGuillamot** [wp-pwa/wp-plugin#50]
It looks like `data-attachment-id=0` is being added when the image is not on the database:
```html
<img class="bttrlazyloading" src="https://www.domain.com/imagenes/2012/01/gasolineras-04.jpg" data-attachment-id="0" data-attachment-id-source="wp-query-transient-hit">
```

It must not be included, because we are breaking all the external images.

```js
content_media: [
0,
0,
0,
0,
0,
0,
]
```

If the image is not found (`id=0`) it should not appear.

Related sites:
https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A19

----

https://frontity.pipedrive.com/deal/44

Size: **(8M)**
Environment: **integration-is-finishing (x6)**
Range: **high (x5)**
Behaviour: **critical (x5)**
Mass: **everyone (x5)**
Miscelanea: **referrer (x3)**
PRIORITY: **[18000]**

**Comment by luisherranz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [peta.diariomotor](https://trello.com/c/uWMbKVJP/1-petadiariomotor)
