### ISSUE TITLE
[13500] API responses with lots of images from transients don't load fast after one day

### ISSUE THREAD

**Issue by DAreRodz** [wp-pwa/wp-plugin#55]
Transients are set with an expiration time in [this line](https://github.com/frontity/wp-plugin/blob/dev/wp-pwa.php#L276), but we want them to never expire.

It looks like we can set `$expire` to 0 to make transients never expire.

Pageviews: **(10M)**
Environment: **integration is finishing (x6)**
Range: **medium (x3)**
Behaviour: **critical (x5)**
Mass: **everyone (x5)**
Referrer: **yes (x3)**
PRIORITY: **[13500]**

----
https://frontity.pipedrive.com/deal/44

**Comment by luisherranz** [comment]
follow deploy
