### ISSUE TITLE
[122] Add support for posts with pagination

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/wp-plugin#58]
As you can see in this post https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A31 the content is divided in different "pages".

- Each page has a different URL (for example https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A32) 
- This behaviour is currently controlled by the theme. It uses the H3 titles to break the post in different pages.
- The theme also inserts numeration at the beginning of each H3 title. These numbers don't come in the content.
- You can navigate to the previous and next post using two navigation buttons.

----
https://frontity.pipedrive.com/deal/153
Site pageviews: **(0.86)**
Extra group sites: **(0)**
Extra group pageviews: **(0)**
Development size: **(13)**
Blocking: **no frontity without it (x10)**
Environment: **integration is starting (x6)**
Reusability potential: **ad-hoc (x1)**
Case Study: **yes (x5)**
PRIORITY: **[122.05]**

**Comment by luisherranz** [comment]
If we go on with @SantosGuillamot idea of keeping the post as it is but sending extra pageviews each time the user reaches a `<h3>`, this is what's needed:

- Modify `analytics.sendPageview()` so it accepts `title` and `location`. (size: 2)
- Add a processor that looks for `<h3>` and injects a `<RouteWaypoint>` to use `sendPageview()`. It must avoid sending the same pageview twice in a row. (size: 8)
- Add a CSR action that scrolls to the relevant `<h3>` if `.html/x` is present in the URL. It can use a smooth scroll, like what we do for hash anchors. (size: 3)

This approach won't modify the URL and title of the pwa, it will only send the pageviews.

**Comment by luisherranz** [comment]
If the customer approves this approach, this issue will become an EPIC. The priority is kept here but the size is removed and added to the child issues.
