### ISSUE TITLE
Screenshot inside the plugin is broken

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/wp-plugin#82]

**Comment by Poliuk** [comment]
![Screen Shot 2018-12-27 at 18.29.25.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58b46c76cb082b1a00bab064/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76216456f46b7191a379e70c2958415d4bbe5d4a1f06a3a3dc78e2a436628f0e0feed2695875c23d42afbd811fbf03bc72d84bd4e3e89850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecc5dff48e34c5dad12336af43b.png)

I've just installed from scratch the latest version of the plugin (v 1.10.5) and the screenshot is broken

The broken img link is:
> https://www.govoid.es/wp-content/plugins/frontity/admin/dist/assets/frontity-theme.9440cb34215896b5164d1756afd90e68.png

**Comment by luisherranz** [comment]
test, no mention

**Comment by luisherranz** [comment]
test mention to @luisherranz

**Comment by luisherranz** [comment]
test mention to @luisherranz

**Comment by luisherranz** [comment]
test mention to @luisherranz

**Comment by luisherranz** [comment]
test mention to @luisherranz
