### ISSUE TITLE
[5] Youtube iframes are not showing in posts

### ISSUE THREAD

**Issue by SantosGuillamot** [wp-pwa/wp-plugin#89]
Youtube iframes are not showing in the next post when loaded through Frontity

https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A42

Checking the API, the iframe is not showing in the content, even if we disable Htmlpurifier

https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A43

However, if we check the page-source it is the first thing in post content

----
https://frontity.pipedrive.com/deal/262
Pageviews: **(0.09)**
Environment: **production (x10)**
Range: **low (x1)**
Behaviour: **not-nice (x1)**
Mass: **everyone (x5)**
PRIORITY: **[5]**

**Comment by luisherranz** [comment]
Could you please ask him how is he inserting that YT video? Using a shortcode? Using a custom field?

**Comment by luisherranz** [comment]
Blocked until the customer answers.

**Comment by DAreRodz** [comment]
@SantosGuillamot any news?

**Comment by SantosGuillamot** [comment]
They told us that they always insert youtube videos adding the url

**Comment by luisherranz** [comment]
Where do they add the url?

**Comment by luisherranz** [comment]
@SantosGuillamot 👆

**Comment by SantosGuillamot** [comment]
He answered this: "Siempre insertamos los vídeos de YouTube colocando directamente la url". I understood they just added the link on WP post editor. If you feel it is not like that I will ask them again

**Comment by luisherranz** [comment]
Ok, so he adds the link in `content` but in the REST API neither the link nor the iframe appear. Is that right?

**Comment by SantosGuillamot** [comment]
Yes, that's right. However, it just happens in some posts. Here we have an example where youtube video is showing:
https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A49

**Comment by luisherranz** [comment]
Are we able to reproduce this issue locally? What happens when we insert a YT link in `content`?

**Comment by SantosGuillamot** [comment]
I tried on test and it is working properly, I am not sure how to reproduce this

**Comment by luisherranz** [comment]
Could you please ask them if they know any difference between a post where the REST API outputs the link and a post where it doesn't? And also: do they have any special YouTube or embed plugins?

**Comment by SantosGuillamot** [comment]
I already asked them if there was any difference between posts and they told me Youtube links were added the same way. I will ask them about Youtube or embed plugins.

**Comment by luisherranz** [comment]
Ok, thanks @SantosGuillamot.

**Comment by SantosGuillamot** [comment]
They told us they are not using these plugins

**Comment by luisherranz** [comment]
Ok, is it possible to get access to their dashboard to take a look?

**Comment by SantosGuillamot** [comment]
I will ask him

**Comment by SantosGuillamot** [comment]
We got access to their dashboard. After evaluating the posts affected, it seems that all of them have a "featured video" instead of a "featured image", so this should be the reason. It might be the same as this req. feature: https://github.com/frontity/saturn-theme/issues/212 so we have asked them to add the custom field "featured_video" to the API

**Comment by luisherranz** [comment]
Where do they get the "featured video" feature from? Is it a plugin or the theme?

**Comment by SantosGuillamot** [comment]
It seems to be the theme "Newspaper"

**Comment by luisherranz** [comment]
Ok. We should investigate if there's a WP plugin to select and expose custom fields in the REST API without people having to actually code. Ping me later and let's have a look.

**Comment by luisherranz** [comment]
I've been searching and there's nothing like it, although it may be possible and useful.

I've created a list of REST API plugins we can create, and added it there:
https://github.com/frontity/wp-plugin/wiki/List-of-REST-API-plugins

For now, just tell them to use a code snippet.

**Comment by luisherranz** [comment]
Should we unblock this?

**Comment by SantosGuillamot** [comment]
This was fixed in this other issue: https://github.com/frontity/saturn-theme/issues/212

The client has to add the custom field "featured_video" with the url on the posts and it will work
